# Generated by Django 4.1.2 on 2022-11-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepad',
            name='title',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
