# Generated by Django 4.1.2 on 2022-11-16 11:19

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_active_note_profile_active_notepad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=user.models.upload_avatar),
        ),
        migrations.AddField(
            model_name='profile',
            name='initials',
            field=models.CharField(default='sss', max_length=3),
            preserve_default=False,
        ),
    ]
